name: Hprofile Actions
on: workflow_dispatch
jobs:
   Testing:
      runs-on: ubuntu-latest
      steps:
         - name: Code Checkout
           uses: Actions/Checkout@v4

         - name: Maven Testing
           run: mvn test

         - name: Checkstyle
           run: mvn checkstyle:checkstyle
           
        #setup java 11 OK
        ###
         - name: Setup Java 11
           uses: Actions/setup-java@v3
           with:
              distribution: temurin
              java-version: '11'

        # Setup sonar-scanner
         - name: Setup SonarQube
           uses: warchant/setup-sonar-scanner@v7
        # Run sonar-scanner
         - name: SonarQube Scan
           run: sonar-scanner
              -Dsonar.host.url=${{ secrets.SONAR_URL }}
              -Dsonar.login=${{ secrets.SONAR_TOKEN }}
              -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
              -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
              -Dsonar.host.url=${{ secrets.SONAR_URL }}
              -Dsonar.login=${{ secrets.SONAR_TOKEN }}
              -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
              -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
              -Dsonar.sources=src/
              -Dsonar.junit.reportsPatch=target/surefire-reports/
              -Dsonar.jacoco.reportsPatch=target/jacoco.exec
              -Dsonar.java.checkstyle.reportsPatch=target/checkstyle-result.xml
              -Dsonar.java.binaries=target/test-classes/com/visualpathit/account